services:
  - type: web
    name: zomato-reels-server
    env: node
    rootDir: server
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
